const {chromium,expect}=require('@playwright/test');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Users/bahti/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe'});try{const p=await b.newPage({viewport:{width:390,height:740}});await p.goto('http://127.0.0.1:8080');await p.locator('[data-cookie-accept]').click();const toggle=p.locator('.menu-toggle');await expect(toggle.locator('.menu-line')).toHaveCount(3);await p.evaluate(()=>{window.originalMenuToggle=document.querySelector('.menu-toggle');document.documentElement.style.scrollBehavior='auto';scrollTo(0,1200)});const before=await toggle.boundingBox();
await toggle.click();await expect(toggle).toHaveAttribute('aria-expanded','true');await expect(toggle).toHaveAttribute('aria-label','Закрыть меню');assert(await p.evaluate(()=>document.querySelector('#menu-dialog').contains(window.originalMenuToggle)));assert.equal(await p.locator('#menu-dialog .dialog-close').count(),0);assert.equal(await p.locator('.menu-toggle').count(),1);assert(await toggle.locator('.menu-line').first().evaluate(el=>el.getAnimations().some(a=>a.effect.getTiming().duration>=300)),'Icon must transition, not swap instantly');
for(const delay of [70,180,300]){await p.waitForTimeout(delay);const box=await toggle.boundingBox();assert(Math.abs(box.x-before.x)<1&&Math.abs(box.y-before.y)<1,'Button moved while panel opened')}
assert(await toggle.locator('.menu-line').first().evaluate(el=>getComputedStyle(el).transform!=='none'));await p.screenshot({path:'docs/qa/menu-morph-open.png'});
await toggle.click();await expect(toggle).toHaveAttribute('aria-expanded','false');await expect(p.locator('#menu-dialog')).not.toBeVisible();await expect(toggle).toBeFocused();assert(await p.evaluate(()=>document.querySelector('.header-actions').contains(window.originalMenuToggle)));assert(Math.abs(await p.evaluate(()=>scrollY)-1200)<1);
await toggle.click();await p.waitForTimeout(100);await p.keyboard.press('Escape');await p.keyboard.press('Escape');await expect(p.locator('#menu-dialog')).not.toBeVisible();await expect(toggle).toHaveAttribute('aria-expanded','false');
await toggle.click();await p.locator('#menu-dialog [data-request]').click();await expect(p.locator('#request-dialog')).toBeVisible();await expect(toggle).toHaveAttribute('aria-expanded','false');await p.keyboard.press('Escape');await expect(p.locator('#request-dialog')).not.toBeVisible();await expect(toggle).toBeFocused();
await toggle.click();await p.setViewportSize({width:430,height:500});await p.waitForTimeout(100);const slot=await p.locator('.menu-toggle-slot').boundingBox(),moved=await toggle.boundingBox();assert(Math.abs(slot.x-moved.x)<1&&Math.abs(slot.y-moved.y)<1);await p.setViewportSize({width:1440,height:900});await expect(p.locator('#menu-dialog')).not.toBeVisible();assert.equal(await p.locator('.menu-toggle-slot').count(),0);
await p.setViewportSize({width:768,height:800});await toggle.click();await p.mouse.click(8,160);await expect(p.locator('#menu-dialog')).not.toBeVisible();await expect(toggle).toHaveAttribute('aria-expanded','false');
await p.setViewportSize({width:320,height:480});await p.emulateMedia({reducedMotion:'reduce'});await toggle.click();assert.equal(await toggle.locator('.menu-line').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await toggle.click();await expect(p.locator('#menu-dialog')).not.toBeVisible();assert.notEqual(await p.evaluate(()=>document.body.style.position),'fixed');
console.log('Same menu button verified: 3 lines morph to X, stable position, one DOM node, click/Escape, modal handoff, focus/scroll restoration, resize and reduced motion.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
