const {chromium}=require('@playwright/test');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const b=await chromium.launch({ignoreDefaultArgs:['--hide-scrollbars'],executablePath:process.env.CHROME_PATH||'C:/Users/bahti/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe'});try{const p=await b.newPage();const report=[];
for(const width of [320,390,768,1024])for(const scroll of [0,1200]){await p.setViewportSize({width,height:740});await p.goto('http://127.0.0.1:8080');if(await p.locator('.cookie-banner').isVisible())await p.locator('[data-cookie-accept]').click();await p.evaluate(async y=>{await document.fonts.ready;document.documentElement.style.scrollBehavior='auto';scrollTo(0,y)},scroll);
const result=await p.evaluate(async()=>{const toggle=document.querySelector('.menu-toggle'),dialog=document.querySelector('#menu-dialog'),panel=document.querySelector('.mobile-menu-panel');function sample(){const r=toggle.getBoundingClientRect(),h=document.querySelector('.site-header').getBoundingClientRect(),p=panel.getBoundingClientRect();return{t:performance.now(),x:r.x,y:r.y,w:r.width,h:r.height,scrollY,headerX:h.x,headerWidth:h.width,panelX:p.x,dialogX:dialog.scrollLeft,dialogY:dialog.scrollTop,height:document.documentElement.scrollHeight,focus:document.activeElement.tagName}}const before=sample(),frames=[];toggle.click();frames.push(sample());const end=performance.now()+600;await new Promise(resolve=>{function frame(){frames.push(sample());if(performance.now()<end)requestAnimationFrame(frame);else resolve()}requestAnimationFrame(frame)});return{before,frames}});
report.push({width,scroll,...result});console.log(JSON.stringify({width,scroll,frames:result.frames.length,firstPanelX:result.frames[0].panelX,lastPanelX:result.frames.at(-1).panelX,maxDialogScroll:Math.max(...result.frames.map(f=>f.dialogX))}));}
fs.writeFileSync('docs/qa/menu-opening-frames.json',JSON.stringify(report,null,2));
for(const r of report){for(const f of r.frames){assert(Math.abs(f.x-r.before.x)<=1,`Button x jump at ${r.width}: ${f.x} vs ${r.before.x}`);assert(Math.abs(f.y-r.before.y)<=1,'Button y jump');assert.equal(f.dialogX,0,'Dialog scrolled sideways');assert.equal(f.dialogY,0,'Dialog scrolled vertically');assert.equal(f.scrollY,r.before.scrollY);assert.equal(f.height,r.before.height)}}
console.log('All opening frames stable.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
